// Package editor opens files in the user's preferred external editor.
// It uses tea.ExecProcess so the Bubble Tea TUI suspends cleanly, restoring
// the alt-screen and full state once the editor process exits.
package editor

import (
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"strings"

	tea "github.com/charmbracelet/bubbletea"
)

// DoneMsg is sent after the editor process exits.
type DoneMsg struct {
	Path string
	Err  error
}

// Open suspends the TUI, launches the preferred editor on path, and sends
// DoneMsg when it returns.
func Open(path string) tea.Cmd {
	cmd, err := Command(findEditor(), path)
	if err != nil {
		return func() tea.Msg { return DoneMsg{Path: path, Err: err} }
	}
	cmd.Stdin = os.Stdin
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return tea.ExecProcess(cmd, func(err error) tea.Msg {
		return DoneMsg{Path: path, Err: err}
	})
}

// Command parses a VISUAL/EDITOR value into executable and arguments, then
// appends the file as one argument. Quotes and escapes group words; shell
// expansion, substitutions, pipelines and redirections are never evaluated.
func Command(value, path string) (*exec.Cmd, error) {
	words, err := splitWords(value)
	if err != nil {
		return nil, err
	}
	if len(words) == 0 || words[0] == "" {
		return nil, errors.New("editor command is empty")
	}
	return exec.Command(words[0], append(words[1:], path)...), nil
}

func splitWords(value string) ([]string, error) {
	var words []string
	var word strings.Builder
	var quote rune
	escaped, started := false, false
	for _, character := range value {
		if escaped {
			word.WriteRune(character)
			escaped = false
			started = true
			continue
		}
		if character == '\\' && quote != '\'' {
			escaped = true
			started = true
			continue
		}
		if quote != 0 {
			if character == quote {
				quote = 0
			} else {
				word.WriteRune(character)
			}
			started = true
			continue
		}
		switch character {
		case '\'', '"':
			quote = character
			started = true
		case ' ', '\t', '\n':
			if started {
				words = append(words, word.String())
				word.Reset()
				started = false
			}
		default:
			word.WriteRune(character)
			started = true
		}
	}
	if escaped || quote != 0 {
		return nil, errors.New("editor command has an unfinished quote or escape")
	}
	if started {
		words = append(words, word.String())
	}
	return words, nil
}

// FindOrCreate looks for a vars file for entityName under baseDir (and its
// parent directory, following Ansible's lookup order):
//
//	<dir>/<subdir>/<entityName>.yml
//	<dir>/<subdir>/<entityName>.yaml
//	<dir>/<subdir>/<entityName>/main.yml
//
// If no file is found, it creates <createDir>/<subdir>/<entityName>.yml where
// createDir is the first directory in which <subdir>/ already exists, falling
// back to baseDir. This prevents accidental creation inside an inventories/
// subdirectory when the actual group_vars/ lives one level up.
func FindOrCreate(baseDir, subdir, entityName string) (string, error) {
	if entityName == "" || entityName == "." || entityName == ".." || filepath.Base(entityName) != entityName {
		return "", fmt.Errorf("invalid inventory entity name for a variables file")
	}
	// Build ordered list of directories to search: baseDir, then its parent.
	searchDirs := []string{baseDir}
	if parent := filepath.Dir(baseDir); parent != baseDir {
		searchDirs = append(searchDirs, parent)
	}

	// 1. Return the first matching existing file.
	for _, dir := range searchDirs {
		for _, ext := range []string{".yml", ".yaml"} {
			p := filepath.Join(dir, subdir, entityName+ext)
			if _, err := os.Stat(p); err == nil {
				return p, nil
			}
		}
		// Directory form: <subdir>/<entityName>/main.yml
		p := filepath.Join(dir, subdir, entityName, "main.yml")
		if _, err := os.Stat(p); err == nil {
			return p, nil
		}
	}

	// 2. Choose where to create: prefer a dir where <subdir>/ already exists.
	createDir := baseDir
	for _, dir := range searchDirs {
		if st, err := os.Stat(filepath.Join(dir, subdir)); err == nil && st.IsDir() {
			createDir = dir
			break
		}
	}

	newPath := filepath.Join(createDir, subdir, entityName+".yml")
	if err := os.MkdirAll(filepath.Join(createDir, subdir), 0o750); err != nil {
		return "", err
	}
	header := fmt.Sprintf("# Variables for %s\n# Generated by lazyansible\n---\n\n", entityName)
	if err := os.WriteFile(newPath, []byte(header), 0o640); err != nil {
		return "", err
	}
	return newPath, nil
}

// findEditor returns the editor binary to use.
// Priority: $VISUAL → $EDITOR → nano → vim → vi.
func findEditor() string {
	for _, env := range []string{"VISUAL", "EDITOR"} {
		if v := os.Getenv(env); v != "" {
			return v
		}
	}
	for _, bin := range []string{"nano", "vim", "vi"} {
		if _, err := exec.LookPath(bin); err == nil {
			return bin
		}
	}
	return "vi"
}
